### ISSUE TITLE
Failed to support multiple versions of numpy

### ISSUE THREAD

**Issue by moble** [conda-forge/quaternion-feedstock#12]
Issue:

This package uses the numpy C-API, and the most recent update to numpy means that it needs to be built separately to support numpy 1.13 and 1.14.  Unfortunately, this package is not dealing with that properly, as seen for example in moble/quaternion#82.  Users with 1.13 are able to conda install this package without upgrading numpy even if it was built on 1.14.

In #10 (now reverted) I tried to improve this recipe to support those versions as separate variants, as described in the documentation [here](https://conda.io/docs/user-guide/tasks/build-packages/variants.html).  Specifically, I added `recipe/conda_build_config.yaml` with

```yaml
numpy:
  - 1.13
  - 1.14
```

and in `meta.yaml` itself, I updated the requirements to include

```yaml
requirements:
  build:
    - numpy {{ numpy }}
   run:
    - numpy {{ numpy }}
```

But after the update completed, trying to install or upgrade the quaternion package leads to a downgrade of numpy to version 1.13.  I verified that I could reproduce this in a fresh environment.  I ran these commands:

```
conda create -y -n quaternion_test python numpy
conda activate quaternion_test
conda install -c conda-forge quaternion
```

The last step gave this output:

```
The following NEW packages will be INSTALLED:

    quaternion:      2018.5.10.13.50.12-py36_1 conda-forge

The following packages will be UPDATED:

    ca-certificates: 2018.03.07-0                          --> 2018.4.16-0           conda-forge
    certifi:         2018.4.16-py36_0                      --> 2018.4.16-py36_0      conda-forge
    openssl:         1.0.2o-h26aff7b_0                     --> 1.0.2o-0              conda-forge

The following packages will be DOWNGRADED:

    numpy:           1.14.3-py36h9d02e6b_0                 --> 1.13.3-py36ha9ae307_4    
```

The rerendering for #10 inserted all sorts of extra builds for both 1.13 and 1.14, with those versions in the names of the builds.  Everything appeared to run correctly, so I merged the PR.  But after the update to anaconda, I found that [the conda package files themselves](https://anaconda.org/conda-forge/quaternion/files) did not actually reference the numpy versions in any way (including the absence of the variant hash I was expecting).  I now see that if I had read through the logs of the CI tests, I would have seen that indeed those files were not generated with any variant information — just the python versions.

What have I done wrong?  How can I ensure that the files are actually built and named differently for the different numpy versions?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at <...>anaconda3/envs/quaternion_test:
#
# Name                    Version                   Build  Channel
ca-certificates           2018.03.07                    0  
certifi                   2018.4.16                py36_0  
intel-openmp              2018.0.0                      8  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1.20170329         hb402a30_2  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
mkl                       2018.0.2                      1  
mkl_fft                   1.0.1            py36h917ab60_0  
mkl_random                1.0.1            py36h78cc56f_0  
ncurses                   6.1                  h0a44026_0  
numpy                     1.14.3           py36h9d02e6b_0  
numpy-base                1.14.3           py36ha9ae307_0  
openssl                   1.0.2o               h26aff7b_0  
pip                       10.0.1                   py36_0  
python                    3.6.5                hc167b69_1  
readline                  7.0                  hc1231fa_4  
setuptools                39.1.0                   py36_0  
sqlite                    3.23.1               hf1716c9_0  
tk                        8.6.7                h35a86e2_3  
wheel                     0.31.0                   py36_0  
xz                        5.2.3                h727817e_4  
zlib                      1.2.11               hf3cbc9b_2  

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : quaternion_test
    active env location : <...>anaconda3/envs/quaternion_test
            shell level : 1
       user config file : <~>/.condarc
 populated config files : <~>/.condarc
          conda version : 4.5.3
    conda-build version : 3.10.2
         python version : 3.6.5.final.0
       base environment : <...>anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : <...>anaconda3/pkgs
                          <~>/.conda/pkgs
       envs directories : <...>anaconda3/envs
                          <~>/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.3 requests/2.18.4 CPython/3.6.5 Darwin/17.5.0 OSX/10.13.4
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```
</details>

**Comment by moble** [comment]
@CJ-Wright @dougalsutherland Since you both commented on this package previously, I'll just ask you two: should I ping anyone in particular when I have this kind of question?  Or will people see this as is?

**Comment by dougalsutherland** [comment]
In general, it's probably best to just @-mention conda-forge/core on things like this. (If you just raise an issue on a feedstock and don't ping anyone else, nobody other than @conda-forge/quaternion – that is, just you – is likely to see it.)

The problem seems to be the former `build` dependency of `numpy >=1.13` (present in [the initial recipe](https://github.com/conda-forge/staged-recipes/pull/5661/files)); that's a problem, because that means it'll build with "whatever version that's at least `1.13`" and say that can run with anything at least 1.13. That doesn't work, as you've seen, because it'll build with whatever the newest version is and claim it works with older versions. Instead, you should build with `numpy 1.13`, and then run with `numpy >=1.13`; that'll then continue to work with only one build (no need for a matrix).

I'm sending a PR now that also switches to the new conda-build 3 format, but really the only change needed should be to change `numpy >=1.13` to `numpy 1.13` in `build`.
